[profile.default]
solc_version = '0.8.23'
src = "contracts"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 8

[fuzz]
runs = 1000

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"
anvil = "http://localhost:8545"

[profile.rpc_storage_caching]
chains = "all"  # or specific chain IDs
endpoints = "all"  # or specific URLs

[etherscan]
arbitrum = { key = "${ETHERSCAN_API_KEY}", chain = "arbitrum" }
arb-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "421614", url = "https://api-sepolia.arbiscan.io/api" }
